steps:
  # Step 1: Set the Google Cloud project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'vanshikatesting'  # Replace with your project ID

  # Step 1.5: Check if the Deployment Manager deployment exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    id: 'check-cluster'
    args:
      - '-c'
      - |
        # Check if the GKE Autopilot cluster deployment exists
        if gcloud deployment-manager deployments describe autopilot-cluster-deployment --quiet; then
          echo "Deployment already exists. Skipping creation."
          exit 0  # Exit successfully to skip the next step
        else
          echo "Deployment not found. Proceeding with creation."
          exit 1  # Exit with an error to proceed to the next step
        fi

  # Step 2: Create the Deployment Manager deployment (only if it does not already exist)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deployment-manager'
      - 'deployments'
      - 'create'
      - 'autopilot-cluster-deployment'
      - '--config'
      - 'gke_autopilot.yaml'
    waitFor:
      - 'check-cluster'  # Only run this step if Step 1.5 failed (exit code 1)

  # Step 3: Get credentials for the GKE Autopilot cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster'
      - '--region'
      - 'us-east1'
      - '--project'
      - 'vanshikatesting'

  # Step 4: Deploy Nginx using kubectl
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'apply'
      - '-f'
      - 'nginx-deployment.yaml'

options:
  logging: CLOUD_LOGGING_ONLY

# Timeout to prevent long-running builds from hanging
#timeout: '600s'
