steps:
  # Step 1: Set the Google Cloud project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'vanshikatesting'  # Replace with your project ID

  # Step 2: Attempt to create the Deployment Manager deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    id: 'create-deployment'
    args:
      - '-c'
      - |
        # Try to create the deployment and handle any error
        if ! gcloud deployment-manager deployments create autopilot-cluster-deployment --config gke_autopilot.yaml; then
          echo "Deployment creation failed, likely because it already exists. Skipping to Nginx deployment."
        fi

  # Step 3: Get credentials for the GKE Autopilot cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster'
      - '--region'
      - 'us-west1'
      - '--project'
      - 'vanshikatesting'

  # Step 4: Deploy Nginx using kubectl
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'apply'
      - '-f'
      - 'nginx-deployment.yaml'

options:
  logging: CLOUD_LOGGING_ONLY

# Timeout to prevent long-running builds from hanging
#timeout: '600s'
