steps:
# Step 2: Set the Google Cloud project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'vanshikatesting'  # Replace with your project ID

  # Step 3: Deploy the Deployment Manager configuration to create the GKE Autopilot cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deployment-manager'
      - 'deployments'
      - 'create'
      - 'autopilot-cluster-deployment'  # The name of your deployment
      - '--config'
      - 'gke_autopilot.yaml'  # Path to your Deployment Manager configuration
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster'  # Replace with your GKE Autopilot cluster name
      - '--region'
      - 'us-east1'        # Replace with the region of your GKE Autopilot cluster
      - '--project'
      - 'vanshikatesting' # Replace with your project ID

  # Step 5: Deploy Nginx using kubectl
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'apply'
      - '-f'
      - 'nginx-deployment.yaml'
  logging: CLOUD_LOGGING_ONLY

# Timeout to prevent long-running builds from hanging
#timeout: '600s'
